/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/add/': RouteRecordInfo<
      '/add/',
      '/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/add/custom': RouteRecordInfo<
      '/add/custom',
      '/add/custom',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/add/recipe/[id]': RouteRecordInfo<
      '/add/recipe/[id]',
      '/add/recipe/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/entry/[id]': RouteRecordInfo<
      '/entry/[id]',
      '/entry/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/onboarding/': RouteRecordInfo<
      '/onboarding/',
      '/onboarding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/foods/': RouteRecordInfo<
      '/settings/foods/',
      '/settings/foods',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/foods/[id]': RouteRecordInfo<
      '/settings/foods/[id]',
      '/settings/foods/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings/foods/new': RouteRecordInfo<
      '/settings/foods/new',
      '/settings/foods/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/preferences': RouteRecordInfo<
      '/settings/preferences',
      '/settings/preferences',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stats/': RouteRecordInfo<
      '/stats/',
      '/stats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/add/index.vue': {
      routes:
        | '/add/'
      views:
        | never
    }
    'src/pages/add/custom.vue': {
      routes:
        | '/add/custom'
      views:
        | never
    }
    'src/pages/add/recipe/[id].vue': {
      routes:
        | '/add/recipe/[id]'
      views:
        | never
    }
    'src/pages/entry/[id].vue': {
      routes:
        | '/entry/[id]'
      views:
        | never
    }
    'src/pages/onboarding/index.vue': {
      routes:
        | '/onboarding/'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/foods/index.vue': {
      routes:
        | '/settings/foods/'
      views:
        | never
    }
    'src/pages/settings/foods/[id].vue': {
      routes:
        | '/settings/foods/[id]'
      views:
        | never
    }
    'src/pages/settings/foods/new.vue': {
      routes:
        | '/settings/foods/new'
      views:
        | never
    }
    'src/pages/settings/preferences.vue': {
      routes:
        | '/settings/preferences'
      views:
        | never
    }
    'src/pages/stats/index.vue': {
      routes:
        | '/stats/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
